server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost

token:
  signing:
    key: "mysupersecretkeyforjwtwhichis256bitlengthorjustappearstobeso"
  refresh:
    token:
      expiration: 2592000000
    signing:
      key: "mysupersecretkeyforjwtwhichis256bitlengthorjustappearstobeso"
  access:
    token:
      expiration: 2592000000 # Set the expiration time for the access token in milliseconds (e.g., 1 hour)